name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    name: Run unit tests

    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2

      - run: go test ./...
